apiVersion: apps/v1
kind: Deployment
metadata:
  name: deal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deal-service
  template:
    metadata:
      labels:
        app: deal-service
    spec:
      containers:
        - name: deal-service
          image: deal-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: deal-service
spec:
  selector:
    app: deal-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
