apiVersion: apps/v1
kind: Deployment
metadata:
  name: deal-servce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deal-servce
  template:
    metadata:
      labels:
        app: deal-servce
    spec:
      containers:
        - name: deal-servce
          image: deal-servce
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deal-servce
spec:
  selector:
    app: deal-servce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
